# Generated by Django 5.2.1 on 2026-04-15 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encurtador',
            name='dt_expiracao',
            field=models.DateField(default=datetime.date(2026, 4, 15)),
        ),
    ]
