# Generated by Django 6.1.1 on 2026-09-30 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0002_encurtador_dt_expiracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encurtador',
            name='dt_expiracao',
            field=models.DateField(default=datetime.date(2027, 9, 29)),
        ),
    ]
